runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:oeEBAuF9eYj1WIk4kyIFkQy2fV9hQ314GIPE8w1HV38=
  APP_STORAGE: /tmp
  DB_USERNAME: tomo
  DB_PASSWORD: tomo
  DB_SOCKET: "/cloudsql/enduring-coil-138923:us-east1:ueponkotsu"
  APP_DEBUG: false
  SESSION_DRIVER : cookie

beta_settings:
  cloud_sql_instances: "enduring-coil-138923:us-east1:ueponkotsu"